### ISSUE TITLE
Basic syntax hightlighting for JSNI

### ISSUE THREAD

**Issue by Chris2011** [ksfreitas/gwt4nb#36]
Don't know whether this is the same or not: https://github.com/ksfreitas/gwt4nb/issues/2

but this is my little piece of code:

``` Java
@Override
public final native void setName(String name) /*-{
   this.@org.smth.smthOthers.model.Item::jso.name = name;
}-*/;
```

what netbeans does is all between /**/ will be shown as comments, this is a normal behaviour and not only for the IDE, as you can see it right here, but this is gwt JavaScript code inside a Java function and what I expect is that GWT4NB should knows it and should ignore those /**/ and bring us syntax hightlighting and code completion to this. Its very hard to figure out errors or smth like that. It's only possible at runtime and debugging. I think this behaviour is available for the eclipse plugin.

Regards

Chris

**Comment by Chris2011** [comment]
Is this project still alive? Other IDE's like IDEA and Eclipse have a lot of GWT support.

**Comment by markiewb** [comment]
Afaik: The plugin for eclipse is developed by Google. The plugin for Idea
is developed Jetbrains. This plugin is created by a dev in his free time.

If you want a specific feature implement it yourself and provide a pull
request. Or make a donation so that the author is motivated to spend his
deserved free time to implement it. My 2 cents

Best regards, markiewb

**Comment by markiewb** [comment]
See https://netbeans.org/bugzilla/show_bug.cgi?id=250751

**Comment by markiewb** [comment]
@ksfreitas started the support years ago

Here is the code, if someone wants to jump in: https://github.com/ksfreitas/NBGwt/commit/dd834e9132cbbf4005642654b4ee9566cdc5f979

**Comment by Chris2011** [comment]
As I see it right, it is already implemented in trunk: https://github.com/ksfreitas/gwt4nb/blob/master/trunk/src/org/netbeans/modules/gwt4nb/JsniLanguage.java

but it doesn't work.

**Comment by Chris2011** [comment]
Maybe this could be an option? https://blogs.oracle.com/geertjan/entry/embedding_javascript_editor_in_java

**Comment by Chris2011** [comment]
So based on the blog entry from Geertjan, I implemented it here: https://github.com/Chris2011/gwt4nb/blob/jsni-feature/branches/standalone_nbm_prj/src/org/netbeans/modules/gwt4nb/JSNISupport.java

![jsnisyntaxhighlighting](https://cloud.githubusercontent.com/assets/795658/19600133/e4e7856c-97a3-11e6-9f62-ee0df94e47ed.png)


So we have syntax highlighting and code completion ONLY for code templates. So no real code completion. I think it's a bit harder for embedded languages. And I got a NPE after I open a maven multi module project. embeddedLanguage is null. If someone can help maybe, Would be great.

**Comment by Chris2011** [comment]
I commented out the null check so the NPE is gone ^^. But should be fixed. Pull request worthy?

**Comment by markiewb** [comment]
@Chris2011: Why not? Improvements are better than nothing.

**Comment by Chris2011** [comment]
You are right.

**Comment by markiewb** [comment]
@Chris2011: Do you know a maven based GWT sample project, where I can try out your feature?

**Comment by Chris2011** [comment]
Unfortunately not, but maybe this? https://github.com/steinsag/gwt-maven-example and add a class with JSNi.

**Comment by markiewb** [comment]
Here are some samples
```
    public static native void alert(String msg) /*-{
  $wnd.alert(msg);
}-*/;

    public static native double getPageStartTime()/*-{
            if (true){
                return new Long();
            }
            return 34;
            }-*/;

    public final native void setName(String name) /*-{
   this.@org.smth.smthOthers.model.Item::jso.name = name;
}-*/;
```
