### ISSUE TITLE
Problems while updating version of GWT

### ISSUE THREAD

**Issue by rocknrollerman** [ksfreitas/gwt4nb#37]
I create new Maven Enterprise Application. I add GWT framework. Library has version 2.0.3. Why? I replace library for new version(any version), there is an error: "Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:1.2:compile (default) on project mavengwt-web: artifact not found - Could not find artifact com.google.gwt:gwt-dev:jar:mac:2.4.0 in central (http://repo.maven.apache.org/maven2)" I tried to install in maven gwt-dev 2.4.0 but no success.Could You tell me what's a problem?

**Comment by markiewb** [comment]
@rocknrollerman: That error isn't related to this plugin. 

Your project has to be runnable from cmdline/plain NB to use this plugin! This plugin will not fix/reroute pom-configuration errors regarding GWT.

Closing as invalid
