### ISSUE TITLE
Build fails with GWT 2.7

### ISSUE THREAD

**Issue by shadoan** [ksfreitas/gwt4nb#38]
When using GWT 2.7.0, builds in Netbeans fail with the following error message:

init:
do-gwt-compile-15:
GWT Compiling client-side code.
Error: Could not find or load main class com.google.gwt.dev.GWTCompiler

When using GWT 2.6.1, builds succeed.

**Comment by tugalsan** [comment]
Hello I am using the latest version of gwt4nb with nb8 and GWT2.7

Everytime, I open up my netbeans, I still need to...
click build and see logs of a failed compilation, 
then click the blue colored text to open up some build xml
then replaceAll (Ctrl+H) GWTCompiler to Compiler
then replaceAll (Ctrl+H) -out to -war
then re-click build again.

It is not critical issue for me as I can fix it but it may be for others.
Could it be not solved yet? Or is sth wrong in my configuration....

best regards

Tugalsan Karaback

**Comment by markiewb** [comment]
@shadoan: Thanks for the PR! I am closing this issue now. 
@tugalsan: File a new issue with more details. I do not know, which are the compilation errors
