### ISSUE TITLE
Support for NetBeans 8.1/8.2

### ISSUE THREAD

**Issue by RickPoleshuck** [ksfreitas/gwt4nb#40]

**Comment by tuxedo0801** [comment]
+1

**Comment by markiewb** [comment]
@ksfreitas: Can you provide me the ownership/co-ownership of this project? I will provide the releases as needed!

**Comment by tuxedo0801** [comment]
Why not fork and do pull-request?

**Comment by TekTimmy** [comment]
+1

**Comment by markiewb** [comment]
@tuxedo0801: This way, I can close issues, commit to this repo and provide releases

**Comment by tuxedo0801** [comment]
@markiewb 
Sure. But:

Last commit on project is about 1 year old. 

There was an aim to create an successor or this project: https://github.com/ksfreitas/NBGwt
Last commit about 2 years ago.

And finally, @ksfreitas did not comment anything last three months on this issue. 

My personal conclusion: This project is dead :-(

So, from my point of view, it would be okay to continue the work on this project with a fork.

**Comment by markiewb** [comment]
@tuxedo0801: I got the user rights from @ksfreitas to manage this repo/issues... Currently I don't use GWT at work, so there is no need for me to invest too much time in this plugin. I own other plugins, which need my attention too. 

If you want something fixed in this plugin, provide a pull request and I would be happy to integrate it!

**Comment by tuxedo0801** [comment]
I'm an absolute GWT noob. I wanted to start learning GWT with NB... but don't find time to install an old version of NB to test it. So I'm waiting for the plugin that works with the current version :-(

Sorry.

**Comment by markiewb** [comment]
@tuxedo0801: You can still download the 8.0 version of the plugin from http://plugins.netbeans.org/plugin/44509/gwt4nb It should be compatible to 8.1
