### ISSUE TITLE
Add support for 2.7/2.8

### ISSUE THREAD

**Issue by Chris2011** [ksfreitas/gwt4nb#42]
GWT 2.8 is out since one and a half week. It should be used too and if it's possible, 2.7 too.

**Comment by markiewb** [comment]
At least some variables have to be updated and we need a tester for it :grin: 

See #26 where 2.6-support has been integrated

**Comment by Chris2011** [comment]
Cool i will have a Look. Thx

**Comment by markiewb** [comment]
Yes, please try it out. https://github.com/ksfreitas/gwt4nb/releases/tag/v2.11.0.1-SN
I only added the constants. You are the tester!
