### ISSUE TITLE
http://plugins.netbeans.org not reachable

### ISSUE THREAD

**Issue by profcav** [ksfreitas/gwt4nb#49]
Hi
I need gwt4nb-2.10.12.12.1.2 but netbeans plugins site is not reachable. How can I get it? 
Thanks
Paolo

**Comment by Chris2011** [comment]
Do you need this specific version? The latest release is 2.11.0.2 https://github.com/ksfreitas/gwt4nb/releases/tag/v2.11.0.2 and I don't think, that you will get there a fewer release.

**Comment by profcav** [comment]
Thank a lot for your answer, unfortunately I need the version for netbeans 8.0

**Comment by profcav** [comment]
Great! It works on netbeans 8.0 too.
